name: Publish to PyPI

on:
  push:
    tags:
      - '*.*.*'

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get tag
        id: tag
        run: |
          echo tag=${GITHUB_REF#refs/tags/} >> $GITHUB_OUTPUT
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Make build
        run: |
          poetry build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: lyrics_client-${{ steps.tag.outputs.tag }}.tar.gz
          path: dist/lyrics_client-${{ steps.tag.outputs.tag }}.tar.gz
      - name: Publish release
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry publish